const ETF_DATA = [

    // Bucket 1 — 30 Days
    {
      ticker: "SGOV",
      name: "iShares 0-3 Month Treasury Bond ETF",
      issuer: "BlackRock",
      bucket: 30,
      yield: 4.03,
      ter: 0.09,
      aum: 35.9,
      adv: 950,
      creditScore: 10,
      creditLabel: "AAA",
      maturity: 0.1
    },
    {
      ticker: "BIL",
      name: "SPDR Bloomberg 1-3 Month T-Bill ETF",
      issuer: "State Street",
      bucket: 30,
      yield: 4.00,
      ter: 0.14,
      aum: 42.7,
      adv: 1200,
      creditScore: 10,
      creditLabel: "AAA",
      maturity: 0.14
    },
    {
      ticker: "GBIL",
      name: "Goldman Sachs Access Treasury 0-1 Yr ETF",
      issuer: "Goldman Sachs",
      bucket: 30,
      yield: 3.95,
      ter: 0.12,
      aum: 7.1,
      adv: 85,
      creditScore: 10,
      creditLabel: "AAA",
      maturity: 0.4
    },
    {
      ticker: "SHV",
      name: "iShares Short Treasury Bond ETF",
      issuer: "BlackRock",
      bucket: 30,
      yield: 4.10,
      ter: 0.15,
      aum: 22.0,
      adv: 320,
      creditScore: 10,
      creditLabel: "AAA",
      maturity: 0.4
    },
    {
      ticker: "ICSH",
      name: "iShares Ultra Short-Term Bond Active ETF",
      issuer: "BlackRock",
      bucket: 30,
      yield: 4.45,
      ter: 0.08,
      aum: 6.5,
      adv: 62,
      creditScore: 8,
      creditLabel: "AA",
      maturity: 0.3
    },
    {
      ticker: "JPST",
      name: "JPMorgan Ultra-Short Income ETF",
      issuer: "JPMorgan",
      bucket: 30,
      yield: 4.52,
      ter: 0.18,
      aum: 28.0,
      adv: 480,
      creditScore: 6,
      creditLabel: "A",
      maturity: 0.5
    },
  
    // Bucket 2 — 90 Days
    {
      ticker: "VGSH",
      name: "Vanguard Short-Term Treasury ETF",
      issuer: "Vanguard",
      bucket: 90,
      yield: 3.90,
      ter: 0.03,
      aum: 18.5,
      adv: 290,
      creditScore: 10,
      creditLabel: "AAA",
      maturity: 1.9
    },
    {
      ticker: "SCHO",
      name: "Schwab Short-Term U.S. Treasury ETF",
      issuer: "Schwab",
      bucket: 90,
      yield: 3.81,
      ter: 0.03,
      aum: 11.2,
      adv: 95,
      creditScore: 10,
      creditLabel: "AAA",
      maturity: 1.9
    },
    {
      ticker: "SHY",
      name: "iShares 1-3 Year Treasury Bond ETF",
      issuer: "BlackRock",
      bucket: 90,
      yield: 3.90,
      ter: 0.15,
      aum: 24.0,
      adv: 680,
      creditScore: 10,
      creditLabel: "AAA",
      maturity: 1.9
    },
    {
      ticker: "BSV",
      name: "Vanguard Short-Term Bond ETF",
      issuer: "Vanguard",
      bucket: 90,
      yield: 3.90,
      ter: 0.03,
      aum: 39.7,
      adv: 410,
      creditScore: 8,
      creditLabel: "AA",
      maturity: 2.6
    },
    {
      ticker: "IGSB",
      name: "iShares 1-5 Yr Investment Grade Corp Bond ETF",
      issuer: "BlackRock",
      bucket: 90,
      yield: 4.10,
      ter: 0.04,
      aum: 26.0,
      adv: 310,
      creditScore: 6,
      creditLabel: "A",
      maturity: 2.8
    },
    {
      ticker: "MINT",
      name: "PIMCO Enhanced Short Maturity Active ETF",
      issuer: "PIMCO",
      bucket: 90,
      yield: 4.60,
      ter: 0.35,
      aum: 12.0,
      adv: 145,
      creditScore: 6,
      creditLabel: "A",
      maturity: 0.5
    },
  
    // Bucket 3 — 180 Days+
    {
      ticker: "VCSH",
      name: "Vanguard Short-Term Corporate Bond ETF",
      issuer: "Vanguard",
      bucket: 180,
      yield: 4.26,
      ter: 0.03,
      aum: 39.5,
      adv: 390,
      creditScore: 6,
      creditLabel: "A",
      maturity: 3.0
    },
    {
      ticker: "SPSB",
      name: "SPDR Portfolio Short Term Corp Bond ETF",
      issuer: "State Street",
      bucket: 180,
      yield: 4.20,
      ter: 0.04,
      aum: 9.8,
      adv: 110,
      creditScore: 6,
      creditLabel: "A",
      maturity: 2.9
    },
    {
      ticker: "ISTB",
      name: "iShares Core 1-5 Year USD Bond ETF",
      issuer: "BlackRock",
      bucket: 180,
      yield: 4.05,
      ter: 0.06,
      aum: 14.2,
      adv: 130,
      creditScore: 8,
      creditLabel: "AA",
      maturity: 2.6
    },
    {
      ticker: "FLOT",
      name: "iShares Floating Rate Bond ETF",
      issuer: "BlackRock",
      bucket: 180,
      yield: 4.70,
      ter: 0.15,
      aum: 18.0,
      adv: 280,
      creditScore: 6,
      creditLabel: "A",
      maturity: 0.1
    },
    {
      ticker: "TFLO",
      name: "iShares Treasury Floating Rate Bond ETF",
      issuer: "BlackRock",
      bucket: 180,
      yield: 4.20,
      ter: 0.15,
      aum: 9.5,
      adv: 120,
      creditScore: 10,
      creditLabel: "AAA",
      maturity: 0.1
    },
    {
      ticker: "NEAR",
      name: "BlackRock Short Maturity Bond Active ETF",
      issuer: "BlackRock",
      bucket: 180,
      yield: 4.55,
      ter: 0.25,
      aum: 3.8,
      adv: 42,
      creditScore: 6,
      creditLabel: "A",
      maturity: 0.5
    }
  
  ];